### ISSUE TITLE
As a prospective college student, I should be able to view a list of colleges with their distances from SaddleBack College

### ISSUE THREAD

**Issue by broadermat70** [NickReardon/CS1D-Project1-College-Touring#1]
### Description: 
After logging in as a student, display list. When clicked, program will display a DB with colleges along with distance from Saddleback address.

### Task:
- When list displayed (prompted)
   - [x] connects to the database, where colleges are stored
   - [x] reads from the database, prints on the window.
   - [x] uses a window index widgets.
   - [x] connects to database, where distances are located.
   - [x] reads from the database. 
   - [x] includes close button on the page.
   - [x]  Display all college campuses
   - [x]  Display total miles from Saddleback College

### Testing: 
 - [x]  Create DB of colleges and distance between Saddleback
 - [x]  The data displayed should be correct
 - [x]  The data/display should only show between Saddleback and no other colleges

### Definition of Done
When requested, a prospective student is able to view a list of college campuses along with the distance between that college and Saddleback

### Story points:  10

**Comment by Hilary325** [comment]
This program is supposed to be really helpful. Many high school students are confused when it comes to choice of college. Personally I applied for many Universities. But I had to look for a list of the educational institutions that offer full-ride scholarships. Here CollegeApps helped me. So, maybe it would be better for your program to include this kind of information. Have you thought about adding it?
