### ISSUE TITLE
As a maintenance Administrator, I should be able to add, remove, and alter the price of traditional souvenirs for each college

### ISSUE THREAD

**Issue by rizzi-trevor** [NickReardon/CS1D-Project1-College-Touring#10]
**Description:**
An administrator should be presented with a list of the colleges and their souvenirs. They should be able to alter the details of each colleges souvenir. This will include adding, deleting, and price-changing for the souvenirs. This will be a separate action from adding completely new colleges and souvenirs from an input file.

**Task:**
-  Select which college to alter souvenirs from
    - [x] [Add] button
    - [x] Choose the college, souvenir, and price when adding
    - [x] [Remove] button
    - [x] Ask for confirmation from the user
    - [x] Upload souvenir to database under corresponding college
    - [x] Remove souvenir elements from a college
    - [x] Ask for confirmation of the deletion
    - [x] Remove the souvenir from the database

**Testing:**
- Editing souvenirs from colleges
    - [x] Implement menu to edit colleges
    - [x] Delete souvenirs
    - [x] Add souvenirs

**Definition of Done**
When completed, administrators will be greeted with an edit menu displaying the colleges and their souvenirs. The administrators will be able to add / delete from any specific college and update souvenirs.

**Points**
8
