### ISSUE TITLE
As a prospective college student, I should be able to display traditional souvenirs from any given college campus.

### ISSUE THREAD

**Issue by broadermat70** [NickReardon/CS1D-Project1-College-Touring#2]
### Description: 
After the student selects a college, the souvenirs from that college should be displayed

### Task:
- When user window open
   - [x]  Get the selected college from dropdown
   - [x]  Press button that will display
   - [x]  Display college name
   - [x]  Display all traditional souvenirs from that college

### Testing: 
 - [x] Create DB of colleges and souvenirs
 - [x] Ensure the chosen college is correct
 - [x] The data displayed should be correct

### Definition of Done
When requested, a prospective student is able to view a list souvenirs from any given campus.

### Story points:  15
