### ISSUE TITLE
As a prospective college student, when planning a trip, i should be able to visit 11 campuses starting at UCI

### ISSUE THREAD

**Issue by broadermat70** [NickReardon/CS1D-Project1-College-Touring#3]
### Description: 
A student should be able to plan a trip to visit all 11 campuses. The trip should be planned efficently by distance for each stop of every campus. The total distance should be calculated as well.

### Task:
- [x] When plan initaited
   - [x]  Display all college campuses
   - [x]  Calculate distance for each stop recursively, starting from UCI
   - [x] Distance calculated should be effective for previous campus visited afterwards.

### Testing: 
 - [x]  Create DB of colleges 
  - [x]  Implement data for distances for all choices of campuses of starting from and ending to.
  - [x]  Implement and test recursive algorithm to make sure the most efficient choice in regards to shortest distance in miles is made for next campus to visit
- [x] Calculate and verify distance traveled

### Definition of Done
When requested, a prospective student is able to plan a trip of visiting the 11 initial colleges, starting from UCI, with the most efficient stops calculated between campuses, along with the correct distance traveled throughout the trip
### Story points:  15
