### ISSUE TITLE
As a prospective college student, I should be offered the option to plan the shortest trip, starting from any chosen school

### ISSUE THREAD

**Issue by broadermat70** [NickReardon/CS1D-Project1-College-Touring#4]
### Description: 
A student should be able to plan a trip starting from any chosen school, in which the program calculates which next campus stop is the most efficient in terms of shortest distance, and so on for the next campus afterwards.

### Task:
- When plan initiated
   - [x] Display all college campuses
   - [x] obtain amount of campuses to be visited
         - [x] check boxes to select campuses
   - [X] Ask user for a 3 character trip id
   - [x] Distance calculated should be effective for previous campus visited afterwards. Dependent of number of campuses visited.
  - [x] Efficient distance should be calculated recursively. Using data for all possible distances to and from.
  - [x] Trip should be added in order to database with a unique ID
  

### Testing: 
 * Create DB of colleges 
  - [x] Implement data for distances for all choices of campuses of starting from and ending to.
  - [x] Implement and test recursive algorithm to make sure the most efficient choice in regards to shortest distance in miles is made for next campus to visit
 - [x] Calculate and verify distance traveled
 - [x] Ensure that tripID must be three characters
 - [x] Prevent the reuse of any tripID - warn the user if theirs is taken

### Definition of Done
When requested, a prospective student is able to select a college and input a trip ID, and plan the most efficient trip among any number of campuses. The program will be able to calculate efficient stops recursively, with the number of colleges being visited as input. The complete trip and its ID will be added to the database.
### Story points:  TBD
