### ISSUE TITLE
As a Maintenance Administrator, I should be able to add new colleges to the database

### ISSUE THREAD

**Issue by rizzi-trevor** [NickReardon/CS1D-Project1-College-Touring#5]
**Description**:
An administrator should be able to add new college campuses that will be available for students to incorporate into their trip plans. They will load the new colleges into the database from the provided input file.

**Task:**
- Adding a college
   - [x] Tab containing colleges.
   - [x] Tab to display all colleges. 
   - [x] [Add] button to add new campuses. 
   - [x] Read input file and data
   - [x] Checks for preexisting colleges to make sure nothing duplicates.
   - [x] Upload data to the SQL database.
   - [x] confirm page to make sure you wanna make the changes.
   - [x] confirm page contains yes or no buttons corresponding to functions to accept or reject the 
          request.
   - [x] Display confirmation menu

**Testing**:
- Adding new colleges
   - [x] Read file into DB
   - [x] Ensure valid input file
   - [x] Prevent adding duplicate colleges
   - [x] Confirm successful addition of new items to DB
   - [x] Prevent adding invalid objects 

**Definition of Done**
When enacted, maintenance admins will be able to select a file containing colleges and their corresponding souvenirs to be added to the DB. The program will read from this file and add any colleges not already in the DB to the DB. 

**Story points: 4**
