### ISSUE TITLE
As a Maintenance Administrator, I should be able to login with access to the management program

### ISSUE THREAD

**Issue by rizzi-trevor** [NickReardon/CS1D-Project1-College-Touring#6]
**Description:**
The program requires a store manager login to access. The login screen will prompt for a username and a password, and will check for valid input.

**Task:**
- [x] Connects to database.
- [x] Reads from database with usernames
- [x] Reads from database with passwords
- [x] Text entry for username with label
- [x] Text entry for password with label
- [x] Text displays when invalid username or password
- [x] [ Login ] button to attempt login

**Testing:**
- [x] Attempt with empty username and/or password
- [x] Attempt with a random string to check database works

**Definition of Done**
Be able to login as an admin using correct username and password.

**Story points: 1**
