### ISSUE TITLE
As a customer, I should be able to see a list of college campuses. 

### ISSUE THREAD

**Issue by farnam13245** [NickReardon/CS1D-Project1-College-Touring#7]
### Description:
The interface should be able to display a list of college campuses with the click of a button. 

### Task:
- [x] Display all of the colleges upon plan trip
- [x] GUI element that displays the database showing each college campus

### Testing:
- [x] Open up the window.
- [x] Check that list printed is correct and up to date. 
- [x] Check to make sure colleges are correctly displayed

Definition of Done
Display an accurate list of the college campuses and their distances to other campuses. 

Story points: TBD
