### ISSUE TITLE
As a prospective college student, I should be able to purchase souvenirs from each campus

### ISSUE THREAD

**Issue by NickReardon** [NickReardon/CS1D-Project1-College-Touring#8]
**Description**:
A student should be able to purchases traditional souvenirs from any and each college campus they visit. The program should keep track of the quantity of the souvenirs purchased at each campus.

**Task:**
- Purchasing souvenirs
   - [ ] Display available souvenirs
   - [ ] Function to choose souvenirs and quantity
   - [ ] Display individual purchase cost
   - [ ] Display total purchase cost
   
 - Tracking purchases
   - [ ] Track the total amount spent at each college campus

 - Display totals
   - [ ] Display total amount spent at each campus
   - [ ] Display grand total spent for all campuses visited

**Testing**:
- Making purchases
   - [ ] Make purchases of multiple quantities and price
   - [ ] Make no purchases

**Definition of Done**
When complete, students on trip will be able to make purchases at any and each of the campuses. They will be able to view how much they spent at each campus, along with the grand total of their trip.

**Story points: 20**
