### ISSUE TITLE
As a customer, I should be able to see the distance from saddleback college to a specific college campus.

### ISSUE THREAD

**Issue by farnam13245** [NickReardon/CS1D-Project1-College-Touring#9]
### Description:
There is a section that shows the distance between every college campus and a selected college.

### Task:
- [x] Display shows a list of colleges and their respective distance.

### Testing:
- [x] Get from the user a selected starting college
- [x] Display all the colleges in the database with their distances from that starting college
- [x] Ensure the distances are correct

### Definition of Done
Be able select a starting point and view the list of colleges and their distances from that selected college. The display should update along with changes and additions to the database

Story points: 4
